# Generated by Django 4.1.1 on 2022-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_mesaage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
